/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder_i4_o3_wce1 (pi0, pi1, pi2, pi3, po0, po1, po2);
  wire _0_;
  wire _1_;
  input pi0;
  input pi1;
  input pi2;
  input pi3;
  output po0;
  output po1;
  output po2;
  assign _0_ = pi2 | pi0;
  assign _1_ = pi3 & pi1;
  assign po1 = _1_ | _0_;
  assign po2 = pi3 ^ pi1;
  assign po0 = 1'h0;
endmodule
