/* Generated by Yosys 0.34+27 (git sha1 7d30f716e, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module axc_abs_diff_i8_o4_wc4_1(in0, in1, in2, in3, in4, in5, in6, in7, out0, out1, out2, out3);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  input in5;
  wire in5;
  input in6;
  wire in6;
  input in7;
  wire in7;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  assign _3_ = ~(_0_ & in4);
  assign out3 = ~(_2_ & _3_);
  assign _0_ = ~in0;
  assign _1_ = ~in4;
  assign _2_ = ~(in0 & _1_);
  assign out0 = 1'h1;
  assign out1 = 1'h1;
  assign out2 = 1'h0;
endmodule

